name: Book Scraper

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest #  GitHub provides a temporary virtual machine called a runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4
          python -m pip install requests requests

      - name: Run scraper
        run: |
          python scripts/scraper.py

      - name: Save updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/raw/books.csv

          git diff --cached --quiet || git commit -m "Update book dataset"

          git push